### ISSUE TITLE
Question: Project Status?

### ISSUE THREAD

**Issue by FredHappyface** [rzhou1999/woosticker#24]
Hi what's the status of this project? Is this something you plan on maintaining?

**Comment by rzhou1999** [comment]
Uh, well, turns out I should really check github once in a while.

So as you might be able to tell, this project is on hold for now. I basically only wrote this app to fulfill a very specific/niche need that I had, and it turns out that the current woosticker build fulfills that personal need wonderfully.... so wonderfully, in fact, that I don't really have motivation to develop further. I see you've been developing a fork of this project-- I'm thrilled that you've taken the time to continue this idea, and I'll update this project's README with a link to your project. But to answer your question more concretely, for all intents and purposes, this project is currently on indefinite hiatus.
