### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by suraj3486** [rzhou1999/woosticker#4]
Please add one 🔎 button at end in top bar where folder icons are shown which will search according to name of files

**Comment by rzhou1999** [comment]
Hm, so I've considered this before and I'm not sure it's even possible. Unlike in-app sticker keyboards or even gboard stickers, woosticker is the *system keyboard* when active-- in order to type in a search term, what would need to happen is that a second keyboard is somehow embedded into the woosticker keyboard. I.e., you would have to replace the woosticker system keyboard with another system keyboard.... but that means woosticker has been closed and thus you can't use it anymore. Are there any apps you have seen that do manage to nest keyboards? I'd be interested in seeing their approach.
